language: java
jdk: 
  - oraclejdk8

#language: python
#python:
#  - "2.7.6"
# sudo: true

install:
   - pip2.7 install --user cwl-runner
#  - git clone https://github.com/common-workflow-language/schema_salad.git
#    # - (cd schema_salad && git checkout 8573af0d63ce43f228b99849aa32615e938166da)
#  - (cd schema_salad && git checkout v1.4)
#  - export PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages/
#  - chmod a+x schema_salad/setup.py
#  - /home/travis/virtualenv/python2.7.6/bin/python schema_salad/setup.py install
#  - wget https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/791f4ef1dea83aed7827b679e179c634db7c0095/draft-3/cwl-avro.yml
   - git clone https://github.com/common-workflow-language/common-workflow-language 
   - python -mschema_salad --print-avro common-workflow-language/draft-3/CommonWorkflowLanguage.yml  > avro.avsc
   - sed '/draft-3.dev/d' avro.avsc > avro.edited.avsc
   - wget https://repo1.maven.org/maven2/org/apache/avro/avro-tools/1.7.7/avro-tools-1.7.7.jar
   - java -jar avro-tools-1.7.7.jar compile schema cwl.edited.avsc cwl-temp
   - rm -Rf cwl
   - sed -i '1i package cwl;' cwl
   - mv cwl-temp cwl

script: cd WIP/alternative/ && mvn -B clean install
