language: java
jdk: 
  - oraclejdk8

install:
   # install a specific version of the cwl dependencies to test with
   - pip2.7 install --user cwl-runner cwltool==1.0.20160108200940 schema-salad==1.4.20160108200836
   - git clone https://github.com/common-workflow-language/common-workflow-language 
   # convert CWL schema salad CWL to standard Avro json
   - python -mschema_salad --print-avro common-workflow-language/draft-3/CommonWorkflowLanguage.yml  > cwl.avsc
   # get rid of invalid avro symbols
   - sed '/draft-3/d' cwl.avsc > cwl.edited.avsc
   - wget https://repo1.maven.org/maven2/org/apache/avro/avro-tools/1.7.7/avro-tools-1.7.7.jar
   # generate Java model classes
   - java -jar avro-tools-1.7.7.jar compile schema cwl.edited.avsc cwl-temp
   # create packages for the classes
   - sed -i '1i package io.cwl.avro;' cwl-temp/*
   - rm -Rf core/src/main/java/cwl/avro
   - cp -R cwl-temp core/src/main/java/cwl/avro    
   - echo "the output below should show that the generated API more-or-less matches the checked-in API for convenience"
   - git diff 

script: mvn -B clean install
