language: java
jdk: 
  - oraclejdk8

sudo: required

install:
   # upgrade pip?
   - sudo pip install --upgrade pip
   # install a specific version of the cwl dependencies to test with
   - pip2.7 install --user setuptools==36.5.0
   - pip2.7 install --user cwl-runner cwltool==1.0.20170828135420 schema-salad==2.6.20170806163416 avro==1.8.1
   - git clone https://github.com/common-workflow-language/common-workflow-language 
   # convert CWL schema salad CWL to standard Avro json
   - python -mschema_salad --print-avro common-workflow-language/v1.0/CommonWorkflowLanguage.yml  > cwl.avsc
   # get rid of invalid avro symbols
   - sed '/draft-3/d' cwl.avsc > cwl.edited.avsc
   - sed -i '/draft-2/d' cwl.edited.avsc
   - sed -i '/draft-4/d' cwl.edited.avsc
   - sed -i '/dev4/d' cwl.edited.avsc
   - sed -i '/v1.0/d' cwl.edited.avsc
   # get rid of symbols that screw up javadoc (not sure if invalid avro schema)
   - sed -i 's/<A>/A/g' cwl.edited.avsc
   - sed -i 's/<B>/B/g' cwl.edited.avsc
   - sed -i 's/<C>/C/g' cwl.edited.avsc
   - wget https://repo1.maven.org/maven2/org/apache/avro/avro-tools/1.8.1/avro-tools-1.8.1.jar
   # generate Java model classes
   - java -jar avro-tools-1.8.1.jar compile schema cwl.edited.avsc cwl-temp
   # create packages for the classes
   - sed -i '1i package io.cwl.avro;' cwl-temp/*
   - sed -i 's/Any/Object/g' cwl-temp/*
   - rm  cwl-temp/Any.java
   - rm -Rf cwlavro-generated/src/main/java/io/cwl/avro
   - cp -R cwl-temp cwlavro-generated/src/main/java/io/cwl/avro    
   - echo "the output below should show that the generated API more-or-less matches the checked-in API for convenience"
   - git diff

jobs:
  include:
  - stage: regular
    script: mvn -B clean install
  # no point in running coverage if we don't pass integration tests
  - stage: coverage
    script: mvn -B clean install jacoco:report jacoco:report-aggregate coveralls:report -Pcoverage

# build lifecycle is before_install, install, before_script, script, after_script

after_success:
  - bash <(curl -s https://codecov.io/bash) -F ${TESTING_PROFILE//-} || echo "Codecov did not collect coverage reports"
  - mvn -B versioneye:update || true
