language: java
jdk: 
  - oraclejdk8

install:
  - docker version
  - pip2.7 install --user cwl-runner
  - git clone https://github.com/common-workflow-language/schema_salad.git
  - chmod a+x schema_salad/setup.py
  - ./schema_salad/setup.py install
  - wget https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/791f4ef1dea83aed7827b679e179c634db7c0095/draft-3/cwl-avro.yml
  - python -mschema_salad --print-avro cwl-avro.yml  > avro.avsc
  - wget https://repo1.maven.org/maven2/org/apache/avro/avro-tools/1.7.7/avro-tools-1.7.7.jar
  - java -jar avro-tools-1.7.7.jar compile schema cwl.avsc cwl-temp
  - rm -Rf cwl
  - sed -i '1i package cwl;' cwl
  - mv cwl-temp cwl

script: mvn -B clean install
