language: java
jdk: 
  - oraclejdk8

install:
   - pip2.7 install --user cwl-runner cwltool==1.0.20160108200940 schema-salad==1.4.20160108200836
   - git clone https://github.com/common-workflow-language/common-workflow-language 
   - python -mschema_salad --print-avro common-workflow-language/draft-3/CommonWorkflowLanguage.yml  > cwl.avsc
   - sed '/draft-3/d' cwl.avsc > cwl.edited.avsc
   - wget https://repo1.maven.org/maven2/org/apache/avro/avro-tools/1.7.7/avro-tools-1.7.7.jar
   - java -jar avro-tools-1.7.7.jar compile schema cwl.edited.avsc cwl-temp
   - sed -i '1i package cwl;' cwl-temp/*
   - rm -Rf WIP/alternative/src/main/java/cwl
   - cp -R cwl-temp WIP/alternative/src/main/java/cwl  
   - echo "the output below should show that the generated API more-or-less matches the checked-in API for convenience"
   - git diff 

script: cd WIP/alternative/ && mvn -B clean install
